encoding: bom|utf-8

title: МеталлВСамаре
email: sammetok@yandex.ru
phones:
  - 8 (927) 260 02 77
  - 8 (846) 990 02 77
address: "пгт. Смышляевка, ул.Аэропорт-2, литер Ж"
description: >- # this means to ignore newlines until "baseurl:"
  Производство, изготовление и монтаж легких металлоконструкций в Самаре!
baseurl: ""
# baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# FOR SCHEMA.ORG
postalCode: "443046"
addressCountry: "Россия"
addressRegion: "Самарская область"
addressLocality: "Самара"
streetAddress: "ул.Аэропорт-2, литер Ж"


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - README.md
  - mix-manifest.json
  - package.json
  - src
  - webpack.mix.js
  - yarn.lock
  - docker-compose.yml
  - package-lock.json
  - tailwind.config.js

collections:
  work-categories:
    output: true
    permalink: /:path/
